version: '3.8'

services:
  tunnelmole:
    image: ghcr.io/robbie-cahill/tunnelmole-service:latest
    env_file: .env
    ports:
      - '8000:8000'
      - '8080:8080'
    volumes:
      - ./config-instance.toml:/app/config-instance.toml:ro
      - ./apiKeys.json:/app/src/authentication/apiKeys.json:ro
    depends_on:
      - mysql
    restart: unless-stopped

  # Optional MySQL service for logging/telemetry if enabled in config-instance.toml
  mysql:
    image: mysql:8.0.32
    container_name: mysql-8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
